# Generated by Django 4.0.1 on 2022-01-25 14:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20)])),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.TimeField(blank=True, null=True)),
                ('end_date', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('available_seats', models.PositiveIntegerField(null=True)),
                ('halls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cinemahallmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('bought_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sessions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionmodel')),
            ],
        ),
    ]
