# Generated by Django 4.0.1 on 2022-01-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cinemahallmodel_sessionmodel_ticketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahallmodel',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
