# Generated by Django 4.0.1 on 2022-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_cinemahallmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahallmodel',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
